//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 7/11/2024 6:53:55 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace PayItGlobal.DTOs.Generated
{

    public static partial class AspNetUserLoginConverter
    {

        public static AspNetUserLoginDto ToDto(this PayItGlobal.Domain.Entities.AspNetUserLogin source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static AspNetUserLoginDto ToDtoWithRelated(this PayItGlobal.Domain.Entities.AspNetUserLogin source, int level)
        {
            if (source == null)
              return null;

            var target = new AspNetUserLoginDto();

            // Properties
            target.LoginProvider = source.LoginProvider;
            target.ProviderKey = source.ProviderKey;
            target.ProviderDisplayName = source.ProviderDisplayName;
            target.UserId = source.UserId;

            // Navigation Properties
            if (level > 0) {
              target.AspNetUser = source.AspNetUser.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static PayItGlobal.Domain.Entities.AspNetUserLogin ToEntity(this AspNetUserLoginDto source)
        {
            if (source == null)
              return null;

            var target = new PayItGlobal.Domain.Entities.AspNetUserLogin();

            // Properties
            target.LoginProvider = source.LoginProvider;
            target.ProviderKey = source.ProviderKey;
            target.ProviderDisplayName = source.ProviderDisplayName;
            target.UserId = source.UserId;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<AspNetUserLoginDto> ToDtos(this IEnumerable<PayItGlobal.Domain.Entities.AspNetUserLogin> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<AspNetUserLoginDto> ToDtosWithRelated(this IEnumerable<PayItGlobal.Domain.Entities.AspNetUserLogin> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<PayItGlobal.Domain.Entities.AspNetUserLogin> ToEntities(this IEnumerable<AspNetUserLoginDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(PayItGlobal.Domain.Entities.AspNetUserLogin source, AspNetUserLoginDto target);

        static partial void OnEntityCreating(AspNetUserLoginDto source, PayItGlobal.Domain.Entities.AspNetUserLogin target);

    }

}
