//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 7/11/2024 6:53:55 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace PayItGlobalApi.DTOs.Generated
{

    public static partial class AspNetUserClaimConverter
    {

        public static AspNetUserClaimDto ToDto(this PayItGlobalApi.Domain.Entities.AspNetUserClaim source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static AspNetUserClaimDto ToDtoWithRelated(this PayItGlobalApi.Domain.Entities.AspNetUserClaim source, int level)
        {
            if (source == null)
              return null;

            var target = new AspNetUserClaimDto();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.ClaimType = source.ClaimType;
            target.ClaimValue = source.ClaimValue;

            // Navigation Properties
            if (level > 0) {
              target.AspNetUser = source.AspNetUser.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static PayItGlobalApi.Domain.Entities.AspNetUserClaim ToEntity(this AspNetUserClaimDto source)
        {
            if (source == null)
              return null;

            var target = new PayItGlobalApi.Domain.Entities.AspNetUserClaim();

            // Properties
            target.Id = source.Id;
            target.UserId = source.UserId;
            target.ClaimType = source.ClaimType;
            target.ClaimValue = source.ClaimValue;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<AspNetUserClaimDto> ToDtos(this IEnumerable<PayItGlobalApi.Domain.Entities.AspNetUserClaim> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<AspNetUserClaimDto> ToDtosWithRelated(this IEnumerable<PayItGlobalApi.Domain.Entities.AspNetUserClaim> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<PayItGlobalApi.Domain.Entities.AspNetUserClaim> ToEntities(this IEnumerable<AspNetUserClaimDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(PayItGlobalApi.Domain.Entities.AspNetUserClaim source, AspNetUserClaimDto target);

        static partial void OnEntityCreating(AspNetUserClaimDto source, PayItGlobalApi.Domain.Entities.AspNetUserClaim target);

    }

}
