//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 7/11/2024 6:53:55 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace PayItGlobalApi.DTOs.Generated
{

    public static partial class AspNetUserTokenConverter
    {

        public static AspNetUserTokenDto ToDto(this PayItGlobalApi.Domain.Entities.AspNetUserToken source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static AspNetUserTokenDto ToDtoWithRelated(this PayItGlobalApi.Domain.Entities.AspNetUserToken source, int level)
        {
            if (source == null)
              return null;

            var target = new AspNetUserTokenDto();

            // Properties
            target.UserId = source.UserId;
            target.LoginProvider = source.LoginProvider;
            target.Name = source.Name;
            target.Value = source.Value;

            // Navigation Properties
            if (level > 0) {
              target.AspNetUser = source.AspNetUser.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static PayItGlobalApi.Domain.Entities.AspNetUserToken ToEntity(this AspNetUserTokenDto source)
        {
            if (source == null)
              return null;

            var target = new PayItGlobalApi.Domain.Entities.AspNetUserToken();

            // Properties
            target.UserId = source.UserId;
            target.LoginProvider = source.LoginProvider;
            target.Name = source.Name;
            target.Value = source.Value;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<AspNetUserTokenDto> ToDtos(this IEnumerable<PayItGlobalApi.Domain.Entities.AspNetUserToken> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<AspNetUserTokenDto> ToDtosWithRelated(this IEnumerable<PayItGlobalApi.Domain.Entities.AspNetUserToken> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<PayItGlobalApi.Domain.Entities.AspNetUserToken> ToEntities(this IEnumerable<AspNetUserTokenDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(PayItGlobalApi.Domain.Entities.AspNetUserToken source, AspNetUserTokenDto target);

        static partial void OnEntityCreating(AspNetUserTokenDto source, PayItGlobalApi.Domain.Entities.AspNetUserToken target);

    }

}
