//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 7/7/2024 2:24:18 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace PayItGlobal.DTOs.Generated
{

    public static partial class AspNetRoleClaimConverter
    {

        public static AspNetRoleClaimDto ToDto(this PayItGlobal.Domain.Entities.AspNetRoleClaim source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static AspNetRoleClaimDto ToDtoWithRelated(this PayItGlobal.Domain.Entities.AspNetRoleClaim source, int level)
        {
            if (source == null)
              return null;

            var target = new AspNetRoleClaimDto();

            // Properties
            target.Id = source.Id;
            target.RoleId = source.RoleId;
            target.ClaimType = source.ClaimType;
            target.ClaimValue = source.ClaimValue;

            // Navigation Properties
            if (level > 0) {
              target.AspNetRole = source.AspNetRole.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static PayItGlobal.Domain.Entities.AspNetRoleClaim ToEntity(this AspNetRoleClaimDto source)
        {
            if (source == null)
              return null;

            var target = new PayItGlobal.Domain.Entities.AspNetRoleClaim();

            // Properties
            target.Id = source.Id;
            target.RoleId = source.RoleId;
            target.ClaimType = source.ClaimType;
            target.ClaimValue = source.ClaimValue;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<AspNetRoleClaimDto> ToDtos(this IEnumerable<PayItGlobal.Domain.Entities.AspNetRoleClaim> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<AspNetRoleClaimDto> ToDtosWithRelated(this IEnumerable<PayItGlobal.Domain.Entities.AspNetRoleClaim> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<PayItGlobal.Domain.Entities.AspNetRoleClaim> ToEntities(this IEnumerable<AspNetRoleClaimDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(PayItGlobal.Domain.Entities.AspNetRoleClaim source, AspNetRoleClaimDto target);

        static partial void OnEntityCreating(AspNetRoleClaimDto source, PayItGlobal.Domain.Entities.AspNetRoleClaim target);

    }

}
