--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8 (Debian 15.8-0+deb12u1)
-- Dumped by pg_dump version 15.3

-- Started on 2024-11-22 13:33:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 32771)
-- Name: core_identity; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA core_identity;


ALTER SCHEMA core_identity OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 32772)
-- Name: asp_net_role_claims; Type: TABLE; Schema: core_identity; Owner: postgres
--

CREATE TABLE core_identity.asp_net_role_claims (
    id integer NOT NULL,
    role_id integer,
    claim_type text,
    claim_value text
);


ALTER TABLE core_identity.asp_net_role_claims OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 32777)
-- Name: asp_net_role_claims_id_seq; Type: SEQUENCE; Schema: core_identity; Owner: postgres
--

CREATE SEQUENCE core_identity.asp_net_role_claims_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE core_identity.asp_net_role_claims_id_seq OWNER TO postgres;

--
-- TOC entry 3433 (class 0 OID 0)
-- Dependencies: 216
-- Name: asp_net_role_claims_id_seq; Type: SEQUENCE OWNED BY; Schema: core_identity; Owner: postgres
--

ALTER SEQUENCE core_identity.asp_net_role_claims_id_seq OWNED BY core_identity.asp_net_role_claims.id;


--
-- TOC entry 217 (class 1259 OID 32778)
-- Name: asp_net_roles; Type: TABLE; Schema: core_identity; Owner: postgres
--

CREATE TABLE core_identity.asp_net_roles (
    id integer NOT NULL,
    name text,
    normalized_name text,
    concurrency_stamp text
);


ALTER TABLE core_identity.asp_net_roles OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 32783)
-- Name: asp_net_roles_id_seq; Type: SEQUENCE; Schema: core_identity; Owner: postgres
--

ALTER TABLE core_identity.asp_net_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME core_identity.asp_net_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 32784)
-- Name: asp_net_user_claims; Type: TABLE; Schema: core_identity; Owner: postgres
--

CREATE TABLE core_identity.asp_net_user_claims (
    id integer NOT NULL,
    user_id integer,
    claim_type text,
    claim_value text
);


ALTER TABLE core_identity.asp_net_user_claims OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 32789)
-- Name: asp_net_user_claims_id_seq; Type: SEQUENCE; Schema: core_identity; Owner: postgres
--

CREATE SEQUENCE core_identity.asp_net_user_claims_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE core_identity.asp_net_user_claims_id_seq OWNER TO postgres;

--
-- TOC entry 3434 (class 0 OID 0)
-- Dependencies: 220
-- Name: asp_net_user_claims_id_seq; Type: SEQUENCE OWNED BY; Schema: core_identity; Owner: postgres
--

ALTER SEQUENCE core_identity.asp_net_user_claims_id_seq OWNED BY core_identity.asp_net_user_claims.id;


--
-- TOC entry 221 (class 1259 OID 32790)
-- Name: asp_net_user_logins; Type: TABLE; Schema: core_identity; Owner: postgres
--

CREATE TABLE core_identity.asp_net_user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id integer
);


ALTER TABLE core_identity.asp_net_user_logins OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 32795)
-- Name: asp_net_user_roles; Type: TABLE; Schema: core_identity; Owner: postgres
--

CREATE TABLE core_identity.asp_net_user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE core_identity.asp_net_user_roles OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 32798)
-- Name: asp_net_user_roles_user_id_seq; Type: SEQUENCE; Schema: core_identity; Owner: postgres
--

CREATE SEQUENCE core_identity.asp_net_user_roles_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE core_identity.asp_net_user_roles_user_id_seq OWNER TO postgres;

--
-- TOC entry 3435 (class 0 OID 0)
-- Dependencies: 223
-- Name: asp_net_user_roles_user_id_seq; Type: SEQUENCE OWNED BY; Schema: core_identity; Owner: postgres
--

ALTER SEQUENCE core_identity.asp_net_user_roles_user_id_seq OWNED BY core_identity.asp_net_user_roles.user_id;


--
-- TOC entry 224 (class 1259 OID 32799)
-- Name: asp_net_user_tokens; Type: TABLE; Schema: core_identity; Owner: postgres
--

CREATE TABLE core_identity.asp_net_user_tokens (
    user_id integer NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text
);


ALTER TABLE core_identity.asp_net_user_tokens OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 32804)
-- Name: asp_net_users; Type: TABLE; Schema: core_identity; Owner: postgres
--

CREATE TABLE core_identity.asp_net_users (
    id integer NOT NULL,
    user_name text,
    normalized_user_name text,
    email text,
    normalized_email text,
    email_confirmed boolean,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean,
    two_factor_enabled boolean,
    lockout_end timestamp with time zone,
    lockout_enabled boolean,
    access_failed_count integer,
    full_name text
);


ALTER TABLE core_identity.asp_net_users OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 32809)
-- Name: asp_net_users_id_seq; Type: SEQUENCE; Schema: core_identity; Owner: postgres
--

CREATE SEQUENCE core_identity.asp_net_users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE core_identity.asp_net_users_id_seq OWNER TO postgres;

--
-- TOC entry 3436 (class 0 OID 0)
-- Dependencies: 226
-- Name: asp_net_users_id_seq; Type: SEQUENCE OWNED BY; Schema: core_identity; Owner: postgres
--

ALTER SEQUENCE core_identity.asp_net_users_id_seq OWNED BY core_identity.asp_net_users.id;


--
-- TOC entry 227 (class 1259 OID 32810)
-- Name: refresh_tokens; Type: TABLE; Schema: core_identity; Owner: postgres
--

CREATE TABLE core_identity.refresh_tokens (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token text NOT NULL,
    expires timestamp with time zone NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    created_by_ip text,
    revoked timestamp with time zone,
    revoked_by_ip text,
    replaced_by_token text,
    reason_revoked text,
    iv text NOT NULL,
    token_hash text NOT NULL
);


ALTER TABLE core_identity.refresh_tokens OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 32816)
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: core_identity; Owner: postgres
--

CREATE SEQUENCE core_identity.refresh_tokens_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE core_identity.refresh_tokens_id_seq OWNER TO postgres;

--
-- TOC entry 3437 (class 0 OID 0)
-- Dependencies: 228
-- Name: refresh_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: core_identity; Owner: postgres
--

ALTER SEQUENCE core_identity.refresh_tokens_id_seq OWNED BY core_identity.refresh_tokens.id;


--
-- TOC entry 229 (class 1259 OID 32817)
-- Name: state_provinces; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.state_provinces (
    stateprovinceid integer NOT NULL,
    stateprovincecode character(3) NOT NULL,
    countryregioncode character varying(3) NOT NULL,
    isonlystateprovinceflag boolean NOT NULL,
    name character varying(50) NOT NULL,
    territoryid integer NOT NULL,
    rowguid uuid NOT NULL,
    modifieddate timestamp without time zone NOT NULL
);


ALTER TABLE public.state_provinces OWNER TO postgres;

--
-- TOC entry 3237 (class 2604 OID 32820)
-- Name: asp_net_role_claims id; Type: DEFAULT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_role_claims ALTER COLUMN id SET DEFAULT nextval('core_identity.asp_net_role_claims_id_seq'::regclass);


--
-- TOC entry 3238 (class 2604 OID 32821)
-- Name: asp_net_user_claims id; Type: DEFAULT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_claims ALTER COLUMN id SET DEFAULT nextval('core_identity.asp_net_user_claims_id_seq'::regclass);


--
-- TOC entry 3239 (class 2604 OID 32822)
-- Name: asp_net_user_roles user_id; Type: DEFAULT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_roles ALTER COLUMN user_id SET DEFAULT nextval('core_identity.asp_net_user_roles_user_id_seq'::regclass);


--
-- TOC entry 3240 (class 2604 OID 32823)
-- Name: asp_net_users id; Type: DEFAULT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_users ALTER COLUMN id SET DEFAULT nextval('core_identity.asp_net_users_id_seq'::regclass);


--
-- TOC entry 3241 (class 2604 OID 32824)
-- Name: refresh_tokens id; Type: DEFAULT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.refresh_tokens ALTER COLUMN id SET DEFAULT nextval('core_identity.refresh_tokens_id_seq'::regclass);


--
-- TOC entry 3413 (class 0 OID 32772)
-- Dependencies: 215
-- Data for Name: asp_net_role_claims; Type: TABLE DATA; Schema: core_identity; Owner: postgres
--

COPY core_identity.asp_net_role_claims (id, role_id, claim_type, claim_value) FROM stdin;
\.


--
-- TOC entry 3415 (class 0 OID 32778)
-- Dependencies: 217
-- Data for Name: asp_net_roles; Type: TABLE DATA; Schema: core_identity; Owner: postgres
--

COPY core_identity.asp_net_roles (id, name, normalized_name, concurrency_stamp) FROM stdin;
\.


--
-- TOC entry 3417 (class 0 OID 32784)
-- Dependencies: 219
-- Data for Name: asp_net_user_claims; Type: TABLE DATA; Schema: core_identity; Owner: postgres
--

COPY core_identity.asp_net_user_claims (id, user_id, claim_type, claim_value) FROM stdin;
\.


--
-- TOC entry 3419 (class 0 OID 32790)
-- Dependencies: 221
-- Data for Name: asp_net_user_logins; Type: TABLE DATA; Schema: core_identity; Owner: postgres
--

COPY core_identity.asp_net_user_logins (login_provider, provider_key, provider_display_name, user_id) FROM stdin;
\.


--
-- TOC entry 3420 (class 0 OID 32795)
-- Dependencies: 222
-- Data for Name: asp_net_user_roles; Type: TABLE DATA; Schema: core_identity; Owner: postgres
--

COPY core_identity.asp_net_user_roles (user_id, role_id) FROM stdin;
\.


--
-- TOC entry 3422 (class 0 OID 32799)
-- Dependencies: 224
-- Data for Name: asp_net_user_tokens; Type: TABLE DATA; Schema: core_identity; Owner: postgres
--

COPY core_identity.asp_net_user_tokens (user_id, login_provider, name, value) FROM stdin;
\.


--
-- TOC entry 3423 (class 0 OID 32804)
-- Dependencies: 225
-- Data for Name: asp_net_users; Type: TABLE DATA; Schema: core_identity; Owner: postgres
--

COPY core_identity.asp_net_users (id, user_name, normalized_user_name, email, normalized_email, email_confirmed, password_hash, security_stamp, concurrency_stamp, phone_number, phone_number_confirmed, two_factor_enabled, lockout_end, lockout_enabled, access_failed_count, full_name) FROM stdin;
25	jon	JON	jon@example.com	JON@EXAMPLE.COM	f	AQAAAAIAAYagAAAAEJDqgMNjCGB/1Y5YXa0QbUBEjvoeSJUj314wblI+8IsnjZqWi0SZIMwJtbEzj+9j/g==	UK4AS6A4JFLIJHSXRP44LR2WA4CRXH44	22f14ab3-e452-4cc0-bf6e-a6cd4d5f0745	\N	f	f	\N	t	0	\N
26	jonranes	JONRANES	jonranes@example.com	JONRANES@EXAMPLE.COM	f	AQAAAAIAAYagAAAAEPA/pLqIX1vhqc1PPglFOJn8YiqbrZ5ifbJryGOu5Nt8LUuh4WeDMaqxF8tRh6eOfQ==	NXGXXED5YHSWTNAVW4GYAEMWEHEN6BPU	23b0aad9-3ca9-4b7c-9401-de39ab55a8cf	\N	f	f	\N	t	0	\N
\.


--
-- TOC entry 3425 (class 0 OID 32810)
-- Dependencies: 227
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: core_identity; Owner: postgres
--

COPY core_identity.refresh_tokens (id, user_id, token, expires, created, created_by_ip, revoked, revoked_by_ip, replaced_by_token, reason_revoked, iv, token_hash) FROM stdin;
\.


--
-- TOC entry 3427 (class 0 OID 32817)
-- Dependencies: 229
-- Data for Name: state_provinces; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.state_provinces (stateprovinceid, stateprovincecode, countryregioncode, isonlystateprovinceflag, name, territoryid, rowguid, modifieddate) FROM stdin;
\.


--
-- TOC entry 3438 (class 0 OID 0)
-- Dependencies: 216
-- Name: asp_net_role_claims_id_seq; Type: SEQUENCE SET; Schema: core_identity; Owner: postgres
--

SELECT pg_catalog.setval('core_identity.asp_net_role_claims_id_seq', 1, false);


--
-- TOC entry 3439 (class 0 OID 0)
-- Dependencies: 218
-- Name: asp_net_roles_id_seq; Type: SEQUENCE SET; Schema: core_identity; Owner: postgres
--

SELECT pg_catalog.setval('core_identity.asp_net_roles_id_seq', 1, false);


--
-- TOC entry 3440 (class 0 OID 0)
-- Dependencies: 220
-- Name: asp_net_user_claims_id_seq; Type: SEQUENCE SET; Schema: core_identity; Owner: postgres
--

SELECT pg_catalog.setval('core_identity.asp_net_user_claims_id_seq', 1, false);


--
-- TOC entry 3441 (class 0 OID 0)
-- Dependencies: 223
-- Name: asp_net_user_roles_user_id_seq; Type: SEQUENCE SET; Schema: core_identity; Owner: postgres
--

SELECT pg_catalog.setval('core_identity.asp_net_user_roles_user_id_seq', 1, false);


--
-- TOC entry 3442 (class 0 OID 0)
-- Dependencies: 226
-- Name: asp_net_users_id_seq; Type: SEQUENCE SET; Schema: core_identity; Owner: postgres
--

SELECT pg_catalog.setval('core_identity.asp_net_users_id_seq', 26, true);


--
-- TOC entry 3443 (class 0 OID 0)
-- Dependencies: 228
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: core_identity; Owner: postgres
--

SELECT pg_catalog.setval('core_identity.refresh_tokens_id_seq', 1, false);


--
-- TOC entry 3246 (class 2606 OID 32826)
-- Name: asp_net_roles KEY_asp_net_roles_concurrency_stamp; Type: CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_roles
    ADD CONSTRAINT "KEY_asp_net_roles_concurrency_stamp" UNIQUE (concurrency_stamp);


--
-- TOC entry 3244 (class 2606 OID 32828)
-- Name: asp_net_role_claims PK_asp_net_role_claims; Type: CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_role_claims
    ADD CONSTRAINT "PK_asp_net_role_claims" PRIMARY KEY (id);


--
-- TOC entry 3249 (class 2606 OID 32830)
-- Name: asp_net_roles PK_asp_net_roles; Type: CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_roles
    ADD CONSTRAINT "PK_asp_net_roles" PRIMARY KEY (id);


--
-- TOC entry 3251 (class 2606 OID 32832)
-- Name: asp_net_user_claims PK_asp_net_user_claims; Type: CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_claims
    ADD CONSTRAINT "PK_asp_net_user_claims" PRIMARY KEY (id);


--
-- TOC entry 3253 (class 2606 OID 32834)
-- Name: asp_net_user_logins PK_asp_net_user_logins; Type: CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_logins
    ADD CONSTRAINT "PK_asp_net_user_logins" PRIMARY KEY (login_provider, provider_key);


--
-- TOC entry 3255 (class 2606 OID 32836)
-- Name: asp_net_user_roles PK_asp_net_user_roles; Type: CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_roles
    ADD CONSTRAINT "PK_asp_net_user_roles" PRIMARY KEY (user_id, role_id);


--
-- TOC entry 3257 (class 2606 OID 32838)
-- Name: asp_net_user_tokens PK_asp_net_user_tokens; Type: CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_tokens
    ADD CONSTRAINT "PK_asp_net_user_tokens" PRIMARY KEY (user_id, login_provider, name);


--
-- TOC entry 3259 (class 2606 OID 32840)
-- Name: asp_net_users PK_asp_net_users; Type: CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_users
    ADD CONSTRAINT "PK_asp_net_users" PRIMARY KEY (id);


--
-- TOC entry 3261 (class 2606 OID 32842)
-- Name: refresh_tokens PK_refresh_tokens; Type: CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.refresh_tokens
    ADD CONSTRAINT "PK_refresh_tokens" PRIMARY KEY (id);


--
-- TOC entry 3263 (class 2606 OID 32844)
-- Name: state_provinces PK_state_provinces; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.state_provinces
    ADD CONSTRAINT "PK_state_provinces" PRIMARY KEY (stateprovinceid);


--
-- TOC entry 3247 (class 1259 OID 32845)
-- Name: KEY_asp_net_roles_normalized_name; Type: INDEX; Schema: core_identity; Owner: postgres
--

CREATE UNIQUE INDEX "KEY_asp_net_roles_normalized_name" ON core_identity.asp_net_roles USING btree (normalized_name);


--
-- TOC entry 3264 (class 2606 OID 32846)
-- Name: asp_net_role_claims FK_asp_net_role_claims_asp_net_roles_0; Type: FK CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_role_claims
    ADD CONSTRAINT "FK_asp_net_role_claims_asp_net_roles_0" FOREIGN KEY (role_id) REFERENCES core_identity.asp_net_roles(id) ON DELETE CASCADE;


--
-- TOC entry 3265 (class 2606 OID 32851)
-- Name: asp_net_user_claims FK_asp_net_user_claims_asp_net_users_0; Type: FK CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_claims
    ADD CONSTRAINT "FK_asp_net_user_claims_asp_net_users_0" FOREIGN KEY (user_id) REFERENCES core_identity.asp_net_users(id) ON DELETE CASCADE;


--
-- TOC entry 3266 (class 2606 OID 32856)
-- Name: asp_net_user_logins FK_asp_net_user_logins_asp_net_users_0; Type: FK CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_logins
    ADD CONSTRAINT "FK_asp_net_user_logins_asp_net_users_0" FOREIGN KEY (user_id) REFERENCES core_identity.asp_net_users(id) ON DELETE CASCADE;


--
-- TOC entry 3267 (class 2606 OID 32861)
-- Name: asp_net_user_roles FK_asp_net_user_roles_asp_net_roles_1; Type: FK CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_roles
    ADD CONSTRAINT "FK_asp_net_user_roles_asp_net_roles_1" FOREIGN KEY (role_id) REFERENCES core_identity.asp_net_roles(id);


--
-- TOC entry 3268 (class 2606 OID 32866)
-- Name: asp_net_user_roles FK_asp_net_user_roles_asp_net_users_0; Type: FK CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_roles
    ADD CONSTRAINT "FK_asp_net_user_roles_asp_net_users_0" FOREIGN KEY (user_id) REFERENCES core_identity.asp_net_users(id);


--
-- TOC entry 3269 (class 2606 OID 32871)
-- Name: asp_net_user_tokens FK_asp_net_user_tokens_asp_net_users_0; Type: FK CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.asp_net_user_tokens
    ADD CONSTRAINT "FK_asp_net_user_tokens_asp_net_users_0" FOREIGN KEY (user_id) REFERENCES core_identity.asp_net_users(id) ON DELETE CASCADE;


--
-- TOC entry 3270 (class 2606 OID 32876)
-- Name: refresh_tokens FK_refresh_tokens_asp_net_users_0; Type: FK CONSTRAINT; Schema: core_identity; Owner: postgres
--

ALTER TABLE ONLY core_identity.refresh_tokens
    ADD CONSTRAINT "FK_refresh_tokens_asp_net_users_0" FOREIGN KEY (user_id) REFERENCES core_identity.asp_net_users(id);


-- Completed on 2024-11-22 13:33:57

--
-- PostgreSQL database dump complete
--

