//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/7/2024 2:04:14 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobal.Domain.Entities
{
    public partial class AspNetRole : IdentityRole<int> {

        public AspNetRole()
        {
            this.AspNetUsers = new List<AspNetUser>();
            this.AspNetRoleClaims = new List<AspNetRoleClaim>();
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string Name { get; set; }

        public virtual string NormalizedName { get; set; }

        public virtual string ConcurrencyStamp { get; set; }

        public virtual IList<AspNetUser> AspNetUsers { get; set; }

        public virtual IList<AspNetRoleClaim> AspNetRoleClaims { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
