//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/1/2024 2:59:24 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobal.Domain.Entities
{
    public partial class AspNetUser : IdentityUser<string> {

        public AspNetUser()
        {
            this.AspNetUserClaims = new List<AspNetUserClaim>();
            this.AspNetUserLogins = new List<AspNetUserLogin>();
            this.AspNetUserTokens = new List<AspNetUserToken>();
            this.RefreshTokens = new List<RefreshToken>();
            this.AspNetRoles = new List<AspNetRole>();
            OnCreated();
        }

        public string Id { get; set; }

        public string? UserName { get; set; }

        public string? NormalizedUserName { get; set; }

        public string? Email { get; set; }

        public string? NormalizedEmail { get; set; }

        public bool? EmailConfirmed { get; set; }

        public string? PasswordHash { get; set; }

        public string? SecurityStamp { get; set; }

        public string? ConcurrencyStamp { get; set; }

        public string? PhoneNumber { get; set; }

        public bool? PhoneNumberConfirmed { get; set; }

        public bool? TwoFactorEnabled { get; set; }

        public DateTime? LockoutEnd { get; set; }

        public bool? LockoutEnabled { get; set; }

        public int? AccessFailedCount { get; set; }

        public string? FullName { get; set; }

        public virtual IList<AspNetUserClaim> AspNetUserClaims { get; set; }

        public virtual IList<AspNetUserLogin> AspNetUserLogins { get; set; }

        public virtual IList<AspNetUserToken> AspNetUserTokens { get; set; }

        public virtual IList<RefreshToken> RefreshTokens { get; set; }

        public virtual IList<AspNetRole> AspNetRoles { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
