//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/7/2024 2:04:14 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Identity;
namespace PayItGlobal.Domain.Entities
{
    public partial class AspNetUser : IdentityUser<int> {

        public AspNetUser()
        {
            this.AspNetRoles = new List<AspNetRole>();
            this.AspNetUserClaims = new List<AspNetUserClaim>();
            this.AspNetUserLogins = new List<AspNetUserLogin>();
            this.AspNetUserTokens = new List<AspNetUserToken>();
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string UserName { get; set; }

        public virtual string NormalizedUserName { get; set; }

        public virtual string Email { get; set; }

        public virtual string NormalizedEmail { get; set; }

        public virtual bool? EmailConfirmed { get; set; }

        public virtual string PasswordHash { get; set; }

        public virtual string SecurityStamp { get; set; }

        public virtual string ConcurrencyStamp { get; set; }

        public virtual string PhoneNumber { get; set; }

        public virtual bool? PhoneNumberConfirmed { get; set; }

        public virtual bool? TwoFactorEnabled { get; set; }

        public virtual DateTime? LockoutEnd { get; set; }

        public virtual bool? LockoutEnabled { get; set; }

        public virtual int? AccessFailedCount { get; set; }

        public virtual IList<AspNetRole> AspNetRoles { get; set; }

        public virtual IList<AspNetUserClaim> AspNetUserClaims { get; set; }

        public virtual IList<AspNetUserLogin> AspNetUserLogins { get; set; }

        public virtual IList<AspNetUserToken> AspNetUserTokens { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
