//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/1/2024 2:59:24 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobal.Domain.Entities
{
    public partial class PayOnlineMerchantCredential {

        public PayOnlineMerchantCredential()
        {
            OnCreated();
        }

        public int CredentialID { get; set; }

        public int? PortalID { get; set; }

        public int PayonlineProcessorID { get; set; }

        public DateTime CreateDate { get; set; }

        public Guid CreatedBy { get; set; }

        public DateTime? EditDate { get; set; }

        public Guid? EditedBy { get; set; }

        public DateTime? LastPwdChg { get; set; }

        public string? ProcessorID { get; set; }

        public string? UserName { get; set; }

        public string? Password { get; set; }

        public string? MerchantID { get; set; }

        public string? Key { get; set; }

        public int? WPOCredentialID { get; set; }

        public int? MobileWorkerID { get; set; }

        public int? ProcessTypeID { get; set; }

        public int? EncKeyID { get; set; }

        public virtual PayOnlinePortal PayonlinePortal { get; set; }

        public virtual PayonlineProcessor CC_Credentail { get; set; }

        public virtual PayonlineProcessor ACH_Credential { get; set; }

        public virtual PayonlineProcessType PayonlineProcessType { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
