//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/1/2024 2:59:24 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobal.Domain.Entities
{
    public partial class PayOnlinePortal {

        public PayOnlinePortal()
        {
            this.PayonlineMerchantCredentials = new List<PayOnlineMerchantCredential>();
            this.PayonlinePayments = new List<Payment>();
            OnCreated();
        }

        public int PayOnlinePortalID { get; set; }

        public string Title { get; set; }

        public DateTime AddedDate { get; set; }

        public DateTime? EditDate { get; set; }

        public Guid AdminUserID { get; set; }

        public string? HeaderColor { get; set; }

        public int? LogoWidth { get; set; }

        public int? LogoHeight { get; set; }

        public string? BGTextColor { get; set; }

        public string? RefundPolicy { get; set; }

        public bool? UsesNameOfBusiness { get; set; }

        public bool? UsesInvoiceNumber { get; set; }

        public bool? UsesDynamicField { get; set; }

        public string? DynamicFieldTitle { get; set; }

        public bool DynamicFieldRequired { get; set; }

        public bool? UsesDynamicField2 { get; set; }

        public string? DynamicField2Title { get; set; }

        public bool DynamicField2Required { get; set; }

        public string? URLSlug { get; set; }

        public int ClientID { get; set; }

        public int PortalTypeID { get; set; }

        public string? HomepageInstructions { get; set; }

        public string? PaymentPageInstructions { get; set; }

        public string? ReceiptExtraText { get; set; }

        public string PaymentTypesAllowed { get; set; }

        public bool UsesInvoices { get; set; }

        public string? BannerText { get; set; }

        public bool UseMasterCard { get; set; }

        public bool UseVisa { get; set; }

        public bool UseAmex { get; set; }

        public bool UsesLoyaltyProgram { get; set; }

        public bool CSCOptional { get; set; }

        public bool UseAnyDaySubscriptions { get; set; }

        public bool UseWeeklySubscriptions { get; set; }

        public bool UseDelayPay { get; set; }

        public string? Processor { get; set; }

        public string? ACHProcessor { get; set; }

        public string? BackgroundImage { get; set; }

        public string? PublicSitePayContainerHeader { get; set; }

        public bool UseDiscover { get; set; }

        public bool UseSplitPay { get; set; }

        public bool SendARReceiptToCustomer { get; set; }

        public bool SendARReceiptToClient { get; set; }

        public bool SendPublicReceiptToClient { get; set; }

        public bool UseNagMail { get; set; }

        public string? ReceiptTitle { get; set; }

        public bool UseQBNames { get; set; }

        public bool UseClientEmailForReceipt { get; set; }

        public int? ClassIDToFilterFor { get; set; }

        public string? ReceiptEmail { get; set; }

        public bool UsesCustomAmountTabulation { get; set; }

        public string? CustomAmountText { get; set; }

        public string? ECommTheme { get; set; }

        public DateTime? LastTsysPwdChg { get; set; }

        public int? ACHPayonlineProcessorID { get; set; }

        public int? CCPayonlineProcessorID { get; set; }

        public int? RetailPayonlineProcessorID { get; set; }

        public string? FailEmail { get; set; }

        public bool Active { get; set; }

        public bool ConvFeeExclude { get; set; }

        public bool InvoiceNumberRequired { get; set; }

        public string? AdobeSignAbbreviation { get; set; }

        public int? LocationId { get; set; }

        public bool ProcessACHAsCCD { get; set; }

        public virtual IList<PayOnlineMerchantCredential> PayonlineMerchantCredentials { get; set; }

        public virtual IList<Payment> PayonlinePayments { get; set; }

        public virtual Client PayonlineClient { get; set; }

        public virtual PayOnlinePortaltype PayonlinePortaltype { get; set; }

        public virtual User User { get; set; }

        public virtual PayonlineProcessor ACHPayOnlineProcessor { get; set; }

        public virtual PayonlineProcessor CCPayOnlineProcessor { get; set; }

        public virtual PayonlineProcessor RetailPayonlineProcessor { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
