//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/1/2024 2:59:24 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobal.Domain.Entities
{
    public partial class PayonlineProcessor {

        public PayonlineProcessor()
        {
            this.MerchantCredentials = new List<PayOnlineMerchantCredential>();
            this.PayOnlineMerchantCredentials_PayonlineProcessorID1 = new List<PayOnlineMerchantCredential>();
            this.ACHPortals = new List<PayOnlinePortal>();
            this.CCPortals = new List<PayOnlinePortal>();
            this.RetailPortals = new List<PayOnlinePortal>();
            OnCreated();
        }

        public int ProcessorID { get; set; }

        public string Name { get; set; }

        public virtual IList<PayOnlineMerchantCredential> MerchantCredentials { get; set; }

        public virtual IList<PayOnlineMerchantCredential> PayOnlineMerchantCredentials_PayonlineProcessorID1 { get; set; }

        public virtual IList<PayOnlinePortal> ACHPortals { get; set; }

        public virtual IList<PayOnlinePortal> CCPortals { get; set; }

        public virtual IList<PayOnlinePortal> RetailPortals { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
