//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/16/2024 1:40:37 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobalApi.Domain.Entities
{
    public partial class RefreshToken {

        public RefreshToken()
        {
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual int UserId { get; set; }

        public virtual string Token { get; set; }

        public virtual DateTime Expires { get; set; }

        public virtual DateTime Created { get; set; }

        public virtual string? CreatedByIp { get; set; }

        public virtual DateTime? Revoked { get; set; }

        public virtual string? RevokedByIp { get; set; }

        public virtual string? ReplacedByToken { get; set; }

        public virtual string? ReasonRevoked { get; set; }

        public string Iv { get; set; }

        public string TokenHash { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
