//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/11/2024 6:53:54 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobal.Domain.Entities
{
    public partial class RefreshToken {

        public RefreshToken()
        {
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual int UserId { get; set; }

        public virtual string Token { get; set; }

        public virtual DateTime Expires { get; set; }

        public virtual DateTime Created { get; set; }

        public virtual string CreatedByIp { get; set; }

        public virtual DateTime? Revoked { get; set; }

        public virtual string RevokedByIp { get; set; }

        public virtual string ReplacedByToken { get; set; }

        public virtual string ReasonRevoked { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
