//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/1/2024 2:59:24 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobal.Domain.Entities
{
    public partial class StateProvince {

        public StateProvince()
        {
            this.Clients = new List<Client>();
            OnCreated();
        }

        public int StateProvinceID { get; set; }

        public string StateProvinceCode { get; set; }

        public string CountryRegionCode { get; set; }

        public bool IsOnlyStateProvinceFlag { get; set; }

        public string Name { get; set; }

        public int TerritoryID { get; set; }

        public Guid RowGuid { get; set; }

        public DateTime ModifiedDate { get; set; }

        public virtual IList<Client> Clients { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
