//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/1/2024 2:59:24 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobal.Domain.Entities
{
    public partial class Transaction {

        public Transaction()
        {
            this.SentToQb = false;
            OnCreated();
        }

        public int TransactionID { get; set; }

        public int? PaymentID { get; set; }

        public DateTime TransactionDate { get; set; }

        public string? Response { get; set; }

        public string? ResponseText { get; set; }

        public string? AuthCode { get; set; }

        public string? TDTransactionID { get; set; }

        public string? AVSResponse { get; set; }

        public string? CVVResponse { get; set; }

        public string? ResponseCode { get; set; }

        public string TransactionType { get; set; }

        public int? SubscriptionID { get; set; }

        public int? RebateID { get; set; }

        public string? CardType { get; set; }

        public int? PortalID { get; set; }

        public string? PayeeID { get; set; }

        public string? Last4CC { get; set; }

        public string? Name { get; set; }

        public string? IPAddress { get; set; }

        public decimal? Amount { get; set; }

        public int? EmployeePaymentID { get; set; }

        public int? EmployeePayoutID { get; set; }

        public bool? SentToQb { get; set; }

        public virtual Payment Payment { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
