//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 7/1/2024 2:59:24 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PayItGlobal.Domain.Entities
{
    public partial class User {

        public User()
        {
            this.IsApproved = true;
            this.EmailConfirmed = false;
            this.AdminClients = new List<Client>();
            this.Payments = new List<Payment>();
            this.Portals = new List<PayOnlinePortal>();
            this.Roles = new List<Role>();
            OnCreated();
        }

        public Guid UserID { get; set; }

        public string? Name { get; set; }

        public DateTime? CreationDate { get; set; }

        public string UserName { get; set; }

        public string? ApplicationName { get; set; }

        public string Email { get; set; }

        public string? Password { get; set; }

        public string? PasswordQuestion { get; set; }

        public string? PasswordAnswer { get; set; }

        public bool IsApproved { get; set; }

        public DateTime? LastActivityDate { get; set; }

        public DateTime? LastLoginDate { get; set; }

        public DateTime? LastPasswordChangedDate { get; set; }

        public bool? IsOnline { get; set; }

        public bool? IsLockedOut { get; set; }

        public DateTime? LastLockedOutDate { get; set; }

        public int? FailedPasswordAttemptCount { get; set; }

        public DateTime? FailedPasswordAttemptWindowStart { get; set; }

        public int? FailedPasswordAnswerAttemptCount { get; set; }

        public DateTime? FailedPasswordAnswerAttemptWindowStart { get; set; }

        public DateTime? LastModified { get; set; }

        public string? Comment { get; set; }

        public int PortalID { get; set; }

        public string? OpenId { get; set; }

        public string? FireFileKey { get; set; }

        public int? ClientID { get; set; }

        public string? ClientCustomerID { get; set; }

        public string? SecurityStamp { get; set; }

        public bool EmailConfirmed { get; set; }

        public int? EncKeyId { get; set; }

        public bool? UsesBeta { get; set; }

        public string? AspNetUserId { get; set; }

        public virtual IList<Client> AdminClients { get; set; }

        public virtual IList<Payment> Payments { get; set; }

        public virtual IList<PayOnlinePortal> Portals { get; set; }

        public virtual IList<Role> Roles { get; set; }

        public virtual Client Client { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
